---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-hunter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-psp-kube-hunter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: kube-hunter
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kube-hunter
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: kube-hunter
      containers:
      - name: kube-hunter
        image: aquasec/kube-hunter
        command: ["python", "kube-hunter.py"]
        args: ["--pod", "--active"]
      restartPolicy: Never
  backoffLimit: 4
